name: 'CI'

on:
  push:
    branches: 
      - main
      - dev
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: './global.json'
      - name: Build and Test
        run: ./scripts/Buid.ps1
        shell: pwsh