name: 'CI'

on:
  push:
    branches: 
      - main
      - dev
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet --version
    - name: Build
      run: dotnet build 
    - name: Test
      run: dotnet test --no-build 
