name: 'RELEASE'

on:
  push:
    branches: 
      - main
    tags:
      - '*.*.*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: './global.json'
      - name: Build and Test
        run: ./scripts/Buid.ps1
        shell: pwsh
      - name: Push to NuGet
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./Push.ps1
        shell: pwsh
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/**/*